version: "3.8"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: blackjack
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mariadb_data:



